// vueApp/frontend/src/App.vue
<template>
	<div id="app" :class="{'hide-menu': !isMenuVisible}">
		<Header title="Cod3r - Base de conhecimento" 
		:hideToggle="false"
		:hideUserDropdown="false"
		/>
		<Content />
		<Menu />
		<Footer />
	</div>
</template>

<script>
import { mapState } from 'vuex'
import Header from './components/template/Header'
import Menu from './components/template/Menu'
import Content from './components/template/Content'
import Footer from './components/template/Footer'

export default {
	name: "App",
	components: { Header, Menu, Content, Footer},
	computed: mapState(['isMenuVisible'])
}
</script>

<style>
	* {
		font-family: "Lato", sans-serif;
	}

	body {
		margin: 0;
	}

	#app {
		-webkit-font-smoothing: antialiased;
		-moz-osx-font-smoothing: grayscale;

		height: 100vh;
		display: grid;
		grid-template-rows: 60px 1fr 40px;
		grid-template-columns: 300px 1fr;
		grid-template-areas: 
			"header header"
			"menu content"
			"menu footer";
	}

	#app.hide-menu {
		grid-template-areas: 
			"header header"
			"content content"
			"footer footer";
	}
</style>

// frontend/src/App.tsx
import './App.css';
import Header from "./components/Header"
import Footer from "./components/Footer"
import Menu from "./components/Menu"
import Content from './components/Content'

function App() {
  return (
    <>

    <div id="app">
    <Header title="Cod3r - Base de Conhecimento"/>
    <Menu />
    <Content />
    <Footer />
    </div>
    </>
  );
}

export default App;
